const LETTERS = ['A','B','C','D'];
let quiz = [], idx = 0, selected = {}, lastSettings = null;
const $ = (id) => document.getElementById(id);
function escapeHTML(s){return String(s ?? '').replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function renderMathText(s){return escapeHTML(s).replace(/\\/g,'\');}
function typeset(){ if(window.MathJax && MathJax.typesetPromise) MathJax.typesetPromise().catch(()=>{}); }
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function getWrongSeqs(){try{return JSON.parse(localStorage.getItem('zian_wrong_seqs')||'[]')}catch(e){return []}}
function setWrongSeqs(arr){localStorage.setItem('zian_wrong_seqs', JSON.stringify([...new Set(arr)])); updateWrongCount();}
function updateWrongCount(){ $('wrongCount').textContent = getWrongSeqs().length; }
function uniqueByContent(list){const seen=new Set(), out=[]; for(const q of list){const key=JSON.stringify([q.answer,q.question,q.options]); if(!seen.has(key)){seen.add(key);out.push(q);}} return out;}
function initTags(){const tags=[...new Set(QUESTIONS.flatMap(q=>q.tags||[]))].sort(); const sel=$('tagFilter'); for(const t of tags){const o=document.createElement('option');o.value=t;o.textContent=t;sel.appendChild(o);}}
function poolQuestions(){let bank=$('bankMode').value; let pool=bank==='unique'?uniqueByContent(QUESTIONS):[...QUESTIONS]; if(bank==='wrong'){const wrong=new Set(getWrongSeqs()); pool=QUESTIONS.filter(q=>wrong.has(q.seq));} const tag=$('tagFilter').value; if(tag!=='all') pool=pool.filter(q=>(q.tags||[]).includes(tag)); const s=parseInt($('startNo').value,10), e=parseInt($('endNo').value,10); if(!Number.isNaN(s)) pool=pool.filter(q=>q.source_id>=s); if(!Number.isNaN(e)) pool=pool.filter(q=>q.source_id<=e); return pool;}
function readSettings(){return {bankMode:$('bankMode').value, tagFilter:$('tagFilter').value, count:$('count').value, quizMode:$('quizMode').value, startNo:$('startNo').value, endNo:$('endNo').value};}
function applySettings(s){if(!s)return; for(const [k,v] of Object.entries(s)){if($(k)) $(k).value=v;}}
function startQuiz(){lastSettings=readSettings(); const pool=poolQuestions(); if(pool.length===0){alert('這個條件沒有題目，可以換成「完整 763 題」或清掉範圍限制。');return;} const n=$('count').value==='all'?pool.length:Math.min(parseInt($('count').value,10),pool.length); quiz=shuffle(pool).slice(0,n); idx=0; selected={}; $('setup').hidden=true; $('result').hidden=true; $('quiz').hidden=false; renderQuestion();}
function scoreNow(){let s=0; for(const q of quiz){if(selected[q.seq]===q.answer)s++;} return s;}
function renderQuestion(){const q=quiz[idx], mode=$('quizMode').value, user=selected[q.seq]; $('qIndex').textContent=`第 ${idx+1} / ${quiz.length} 題`; $('bar').style.width=((idx+1)/quiz.length*100)+'%'; $('scoreBadge').textContent=`目前 ${scoreNow()} / ${Object.keys(selected).length}`; $('meta').textContent=`題庫序號 ${q.seq}｜PDF 原題號 ${q.source_id}｜分類：${(q.tags||[]).join('、')}`; $('question').innerHTML=renderMathText(q.question); const box=$('options'); box.innerHTML=''; for(const l of LETTERS){const b=document.createElement('button'); b.className='opt'; b.type='button'; b.innerHTML=`<b>${l}.</b> ${renderMathText(q.options?.[l]||'')}`; if(user){ if(l===q.answer)b.classList.add('correct'); if(l===user&&user!==q.answer)b.classList.add('wrong'); } b.onclick=()=>choose(l); box.appendChild(b);} const fb=$('feedback'); if(user&&mode==='practice'){fb.hidden=false; fb.innerHTML=(user===q.answer?'✅ 答對了！':'❌ 答錯了。')+` 正確答案是 <b>${q.answer}</b>：${renderMathText(q.options[q.answer])}`;}else{fb.hidden=true; fb.innerHTML='';} $('prevBtn').disabled=idx===0; $('nextBtn').textContent=idx===quiz.length-1?'最後一題':'下一題'; typeset();}
function choose(l){const q=quiz[idx]; selected[q.seq]=l; const wrong=getWrongSeqs(); if(l!==q.answer) setWrongSeqs([...wrong,q.seq]); else setWrongSeqs(wrong.filter(x=>x!==q.seq)); renderQuestion();}
function nextQ(){if(idx<quiz.length-1){idx++;renderQuestion();}else showResult();}
function prevQ(){if(idx>0){idx--;renderQuestion();}}
function showResult(){if(!quiz.length)return; $('quiz').hidden=true; $('result').hidden=false; const total=quiz.length, answered=Object.keys(selected).length, score=scoreNow(); $('summary').innerHTML=`你答對 <b>${score}</b> / ${total} 題，正確率 <b>${Math.round(score/total*100)}</b>%。已作答 ${answered} 題。`; const review=$('review'); review.innerHTML=''; for(const [i,q] of quiz.entries()){const user=selected[q.seq]; if(user!==q.answer){const div=document.createElement('div'); div.className='reviewItem'; div.innerHTML=`<b>第 ${i+1} 題｜PDF 原題號 ${q.source_id}</b><br>${renderMathText(q.question)}<br><span class="muted">你的答案：${user||'未作答'}；正確答案：${q.answer} ${renderMathText(q.options[q.answer])}</span>`; review.appendChild(div);}} if(!review.innerHTML) review.innerHTML='<p>太強了，這次沒有錯題！</p>'; typeset();}
function backSetup(){ $('quiz').hidden=true; $('result').hidden=true; $('setup').hidden=false; }
function doSearch(){const kw=$('searchInput').value.trim().toLowerCase(), box=$('searchResult'); box.innerHTML=''; if(!kw){box.innerHTML='<p class="muted">輸入關鍵字後可以快速查題。</p>';return;} const res=QUESTIONS.filter(q=>(q.question+' '+Object.values(q.options||{}).join(' ')+' '+(q.tags||[]).join(' ')).toLowerCase().includes(kw)).slice(0,80); box.innerHTML=`<p class="muted">找到 ${res.length} 筆（最多顯示 80 筆）。</p>`; for(const q of res){const d=document.createElement('details'); d.innerHTML=`<summary>題庫序號 ${q.seq}｜原題號 ${q.source_id}｜${renderMathText(q.question)}</summary><p>A. ${renderMathText(q.options.A)}</p><p>B. ${renderMathText(q.options.B)}</p><p>C. ${renderMathText(q.options.C)}</p><p>D. ${renderMathText(q.options.D)}</p><p><b>答案：${q.answer}</b></p>`; box.appendChild(d);} typeset();}
window.addEventListener('DOMContentLoaded',()=>{if(!window.QUESTIONS){alert('題庫 questions.js 沒有載入，請確認四個檔案都在同一個資料夾。');return;} $('statAll').textContent=QUESTIONS.length; $('statUnique').textContent=uniqueByContent(QUESTIONS).length; updateWrongCount(); initTags(); $('startBtn').addEventListener('click',startQuiz); $('nextBtn').addEventListener('click',nextQ); $('prevBtn').addEventListener('click',prevQ); $('finishBtn').addEventListener('click',showResult); $('backBtn').addEventListener('click',backSetup); $('againBtn').addEventListener('click',()=>{applySettings(lastSettings); startQuiz();}); $('homeBtn').addEventListener('click',backSetup); $('wrongBtn').addEventListener('click',()=>{$('bankMode').value='wrong';startQuiz();}); $('clearWrongBtn').addEventListener('click',()=>{setWrongSeqs([]);alert('錯題本已清空。');}); $('searchBtn').addEventListener('click',doSearch); $('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch();});});
